[features]
seeds = false

[programs.localnet]
solana_blockchain_index = "7kARzULggbgDSLLpBgERNHQSpkse1qM3RB4NEEvS3ztu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "mainnet-beta" # url of the cluster that accounts are cloned from

[[test.validator.account]]
address = "3pyn4svBbxJ9Wnn3RVeafyLWfzie6yC5eTig2S62v9SC"
filename = "tests/ada_price_account.json"

[[test.validator.account]]
address = "Ax9ujW5B9oqcv59N8m6f1BpTBq2rGeGaBcpKjC5UYsXU"
filename = "tests/avax_price_account.json"

[[test.validator.account]]
address = "5ALDzwcRJfSyGdGyhP3kP628aqBNHZzLuVww7o9kdspe"
filename = "tests/bch_price_account.json"

[[test.validator.account]]
address = "4CkQJBxhU8EZ2UjhigbtdaPbpTe6mqf811fipYBFbSYN"
filename = "tests/bnb_price_account.json"

[[test.validator.account]]
address = "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU"
filename = "tests/btc_price_account.json"

[[test.validator.account]]
address = "FsSM3s38PX9K7Dn6eGzuE29S2Dsk1Sss1baytTQdCaQj"
filename = "tests/doge_price_account.json"

[[test.validator.account]]
address = "EcV1X1gY2yb4KXxjVQtTHTbioum2gvmPnFk4zYAt7zne"
filename = "tests/dot_price_account.json"

[[test.validator.account]]
address = "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB"
filename = "tests/eth_price_account.json"

[workspace]
types = "app/src/idl/"
