[features]
seeds = false

[programs.localnet]
solana_blockchain_index = "7kARzULggbgDSLLpBgERNHQSpkse1qM3RB4NEEvS3ztu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "mainnet-beta" # url of the cluster that accounts are cloned from

[[test.validator.account]]
address = "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU"
filename = "tests/btc_price_account.json"

[[test.validator.account]]
address = "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB"
filename = "tests/eth_price_account.json"

[workspace]
types = "app/src/idl/"
