---
name: CI
on:
  pull_request:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set default rust toolchain
        run: rustup default stable

      # unit tests
      - name: Cache Rust crates
        uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # integration tests
      - name: Generate new keypair
        run: solana-keygen new

      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899

      - name: Check solana config
        run: solana config get

      - name: Install yarn dependencies
        run: yarn install

      - name: Build
        run: anchor build

      - name: Run integration tests
        run: anchor test
